### ISSUE TITLE
Support for Fiction database

### ISSUE THREAD

**Issue by mudew** [JoshuaRLi/pylibgen#4]
Libgen has different databases (SciTech, Fiction, etc..) which can be selected while searching here http://gen.lib.rus.ec/.

If I understand correctly, right now it only searches the SciTech database (default). Does pylibgen support (or plans to support), for instance, the Fiction database? If not, what would be needed to implement this?

**Comment by joshuarli** [comment]
You are correct, as far as I know.  I looked into it a little further and you can pass `lg_topic` to `search.php` to specify the database. If it isn't passed (as is current implementation), then SciTech is the default.

Furthermore, `json.php`, which `pylibgen` uses to look up book metadata, only works for "ids" (if you don't supply that parameter, it will spit back `WHERE IDS?`) which only apply to the SciTech database.

**Comment by joshuarli** [comment]
Library Genesis is beautiful and...kinda messy. In addition to these databases having different schemas and front ends which would all need to be scraped differently, In addition, I found out today that SciTech file hosts (e.g. bookfi.net) have different interfaces - it just so happens that libgen.io is both a search engine mirror and a file host mirror as well, which is why I didn't notice this before.

That being said, I am planning a 2.0 rewrite soon to address all this stuff, but if you need to programmatically interact with another database, I would suggest writing your scripts for now.

**Comment by mudew** [comment]
Cool. I will be happy to contribute if you have a plan on how to proceed.

**Comment by joshuarli** [comment]
Hi, would like to say that 2.0.1 has been (finally) released, but I did not include support for the fiction database. Feel free to fork and hack on it if you want!
